#%RAML 1.0 NamedExample
value:
  
  - 
    ID: 1 
    firstname: kapil
    lastname: mediratta
    age: 34
    email: kapilnice@gmail.com
    phone: 9818814855
    type: admin
   
  - 
    ID: 2 
    firstname: testfirstname
    lastname: testlastname
    age: 35
    email: test@test.com
    phone: 1234567890
    type: standard
  